import {NativeModules} from 'react-native';

const languageTheme = {
  en: {
    header_text_home: 'Home',
    header_text_explore: 'Explore',
    header_text_cart: 'Cart',
    header_text_account: 'Account',
    header_text_favorite: 'Favorite',
    header_text_notification: 'Notification',
    header_text_filter: 'Filter',
    header_text_recipient_info: 'Receipt Info',
    header_text_checkout: 'Checkout',
    header_text_profile: 'Profile',
    header_text_address: 'Address',
    header_text_insert_address: 'New Address',
    header_text_card: 'User Card',
    header_text_insert_card: 'New Card',
    header_text_order: 'User Order',
    header_text_order_details: 'Order Details',
    header_text_promocodes: 'Promocodes',
    header_text_product_detail: 'Product Details',
    header_text_product_ratings: 'Ratings',
    header_text_product_insert_rating: 'New Ratings',
    header_text_update_user: 'Update User Info',

    login_text_header: 'Welcome To Computer Store',
    login_text_sub_header: 'Sign In To Continue',
    login_text_other_signin_option: 'Or Sign In With',
    login_button_signin: 'Sign In',
    login_button_forgot_password: 'Forgot Password',
    login_button_google_signin: 'Google',
    login_button_signup_1: "Don't have an account?",
    login_button_signup_2: 'Sign Up here',

    verify_text_description: 'We will send a verification code to your email',
    verify_text_code_description: 'Please verify before the timer expire',
    verify_button_send: 'Send',
    verify_button_signin_1: 'Already have an account?',
    verify_button_signin_2: 'Sign In here',
    verify_button_resend: 'Resend verification code',
    verify_button_verify: 'Verify',

    changePass_button_confirm: 'Confirm',

    signUp_button_confirm: 'Confirm',

    home_text_banner: 'Welcome To Computer Store',
    home_text_popular: 'Popular',
    home_text_best_buy: 'Best Buy',
    home_text_likeable: 'You Might Like',
    home_text_see_more: 'See more',

    explore_text_result: 'Result(s)',
    explore_text_filter: 'Filter',
    explore_option_header: 'Sort By',
    explore_option_1: 'Popularity',
    explore_option_2: 'New',
    explore_option_3: 'Price Low To High',
    explore_option_4: 'Price Hight To Low',

    cart_text_total: 'Total',
    cart_button_order: 'Place Order',

    cartRecipient_button_continue: 'Continue To Checkout',

    checkOut_text_product_price: 'Product(s) Price',
    checkOut_text_shipping_price: 'Shipping Price',
    checkOut_text_summary: 'Summary',
    checkOut_button_place_order: 'Place Order',

    address_button_insert: 'Add New Address',

    insertAddress_button_insert: 'Add',
    insertAddress_button_update: 'Edit',

    account_tabHeader_myOrder: 'My Order',
    account_tabSub_myOrder: 'Order(s) In Progress',
    account_tabHeader_adderss: 'Shipping address',
    account_tabSub_adderss: 'Address(s)',
    account_tabHeader_payment: 'Payment Methods',
    account_tabSub_payment: '',
    account_tabHeader_promo: 'Promocodes',
    account_tabSub_promo: 'Promocode(s) Available',
    account_tabHeader_changePass: 'Change Password',
    account_tabSub_changePass: 'Change Your Password',
    account_tabHeader_logout: 'Logout',
    account_tabSub_logout: 'Logout Of Your Account',

    order_text_orderNumber: 'Order No.',
    order_text_quantity: 'Quantity',
    order_text_total: 'Total',
    order_text_status: 'Status',
    order_button_detail: 'Detail',

    orderDetail_textHeader_order: 'Order',
    orderDetail_textHeader_product: 'Product(s)',
    orderDetail_textHeader_info: 'Order Information',
    orderDetail_text_orderNumber: 'No.',
    orderDetail_text_orderDate: 'Order Date',
    orderDetail_text_orderStatus: 'Order Status',
    orderDetail_text_shippingAddress: 'Shipping Address',
    orderDetail_text_payment: 'Payment Method',
    orderDetail_text_total: 'Total',
    orderDetail_text_discount: 'Discount',
    orderDetail_text_discountCode: 'Discount Code',

    placeholder_username: 'Username',
    placeholder_fullname: 'Fullname',
    placeholder_password: 'Password',
    placeholder_password_confirm: 'Confirm Password',
    placeholder_email: 'Email',
    placeholder_phoneNumber: 'Phone Number',
    placeholder_birthday: 'Birthday',
    placeholder_verify: 'Verification code',
    placeholder_recipient: 'Recipient',
    placeholder_addressName: 'Address Name',
    placeholder_ward: 'Ward',
    placeholder_district: 'District',
    placeholder_city: 'City',

    arr_status_order_0: 'Cancel',
    arr_status_order_1: 'Processing',
    arr_status_order_2: 'Packing',
    arr_status_order_3: 'On the way',
    arr_status_order_4: 'Delivered',

    arr_status_address_0: 'Deactive',
    arr_status_address_1: 'Default',
    arr_status_address_2: 'Optional',

    arr_explore_sort_0: 'None',
    arr_explore_sort_1: 'Popularity',
    arr_explore_sort_2: 'New',
    arr_explore_sort_3: 'Price Ascending',
    arr_explore_sort_4: 'Price Descending',

    err_empty: 'Fields cannot be empty',
    err_signin_wrong: 'Wrong username or password',
    err_nav: 'Invalid navigation',
    err_verify_code: 'Invalid Verification Code',
  },
  de: {
    header_text_home: 'Startseite',
    header_text_explore: 'Erkunden Sie',
    header_text_cart: 'Warenkorb',
    header_text_account: 'Konto',
    header_text_favorite: 'Favorit',
    header_text_notification: 'Benachrichtigung',
    header_text_filter: 'Filtern',
    header_text_recipient_info: 'Quittungs-Infos',
    header_text_checkout: 'Kasse',
    header_text_profile: 'Profil',
    header_text_address: 'Adresse',
    header_text_insert_address: 'Neue Adresse',
    header_text_card: 'Benutzerkarte',
    header_text_insert_card: 'Neue Karte',
    header_text_order: 'Benutzer Bestellung',
    header_text_order_details: 'Details zur Bestellung',
    header_text_promocodes: 'Werbegeschenke',
    header_text_product_detail: 'Produkt-Details',
    header_text_product_ratings: 'Bewertungen',
    header_text_product_insert_rating: 'Neue Bewertungen',
    header_text_update_user: 'Benutzerinformationen aktualisieren',

    login_text_header: 'Willkommen bei Computer Store',
    login_text_sub_header: 'Zum Fortfahren anmelden',
    login_text_other_signin_option: 'Oder Anmelden mit',
    login_button_signin: 'Anmelden',
    login_button_forgot_password: 'Passwort vergessen',
    login_button_google_signin: 'Google',
    login_button_signup_1: 'Sie haben noch kein Konto?',
    login_button_signup_2: 'Hier anmelden',

    verify_text_description:
      'Wir senden Ihnen einen Bestätigungscode an Ihre E-Mail',
    verify_text_code_description:
      'Bitte überprüfen Sie den Code, bevor der Timer abläuft',
    verify_button_send: 'Senden Sie',
    verify_button_signin_1: 'Haben Sie bereits ein Konto?',
    verify_button_signin_2: 'Hier anmelden',
    verify_button_resend: 'Verifizierungscode erneut senden',
    verify_button_verify: 'Überprüfen Sie',

    changePass_button_confirm: 'Bestätigen Sie',

    signUp_button_confirm: 'Bestätigen Sie',

    home_text_banner: 'Willkommen bei Computer Store',
    home_text_popular: 'Beliebt',
    home_text_best_buy: 'Bester Kauf',
    home_text_likeable: 'Könnte Ihnen gefallen',
    home_text_see_more: 'Mehr sehen',

    explore_text_result: 'Ergebnis(se)',
    explore_text_filter: 'Filter',
    explore_option_header: 'Sortieren nach',
    explore_option_1: 'Beliebtheit',
    explore_option_2: 'Neu',
    explore_option_3: 'Preis niedrig bis hoch',
    explore_option_4: 'Preis hoch bis niedrig',

    cart_text_total: 'Gesamt',
    cart_button_order: 'Bestellung aufgeben',

    cartRecipient_button_continue: 'Weiter zur Kasse',

    checkOut_text_product_price: 'Produkt(e) Preis',
    checkOut_text_shipping_price: 'Versandpreis',
    checkOut_text_summary: 'Zusammenfassung',
    checkOut_button_place_order: 'Bestellung aufgeben',

    address_button_insert: 'Neue Adresse hinzufügen',

    insertAddress_button_insert: 'hinzufügen',
    insertAddress_button_update: 'Bearbeiten',

    account_tabHeader_myOrder: 'Meine Bestellung',
    account_tabSub_myOrder: 'Bestellung(en) in Bearbeitung',
    account_tabHeader_adderss: 'Lieferadresse',
    account_tabSub_adderss: 'Anschrift(en)',
    account_tabHeader_payment: 'Zahlungsarten',
    account_tabHeader_promo: 'Werbegeschenke',
    account_tabSub_promo: 'Promo-Code(s) verfügbar',
    account_tabHeader_changePass: 'Passwort ändern',
    account_tabSub_changePass: 'Ändern Sie Ihr Passwort',
    account_tabHeader_logout: 'Abmelden',
    account_tabSub_logout: 'Von Ihrem Konto abmelden',

    order_text_orderNumber: 'Auftrag Nr.',
    order_text_quantity: 'Menge',
    order_text_total: 'Gesamt',
    order_text_status: 'Status',
    order_button_detail: 'Einzelheiten',

    orderDetail_textHeader_order: 'Bestellung',
    orderDetail_textHeader_product: 'Produkt(e)',
    orderDetail_textHeader_info: 'Informationen zur Bestellung',
    orderDetail_text_orderNumber: 'Nr.',
    orderDetail_text_orderDate: 'Datum der Bestellung',
    orderDetail_text_orderStatus: 'Status der Bestellung',
    orderDetail_text_shippingAddress: 'Lieferadresse',
    orderDetail_text_payment: 'Zahlungsmethode',
    orderDetail_text_total: 'Gesamt',
    orderDetail_text_discount: 'Rabatt',
    orderDetail_text_discountCode: 'Rabatt-Code',

    placeholder_username: 'Benutzername',
    placeholder_fullname: 'Vollständiger Name',
    placeholder_password: 'Kennwort',
    placeholder_password_confirm: 'Bestätigen Sie Ihr Passwort',
    placeholder_email: 'E-Mail',
    placeholder_phoneNumber: 'Telefon Nummer',
    placeholder_birthday: 'Geburtstag',
    placeholder_verify: 'Verifizierungs-Code',
    placeholder_recipient: 'Empfänger',
    placeholder_addressName: 'Adresse Name',
    placeholder_ward: 'Bezirk',
    placeholder_district: 'Bezirk',
    placeholder_city: 'Stadt',

    arr_status_order_0: 'Abbrechen',
    arr_status_order_1: 'Verarbeitung',
    arr_status_order_2: 'Verpacken',
    arr_status_order_3: 'Unterwegs',
    arr_status_order_4: 'Geliefert',

    arr_status_address_0: 'Deaktiviert',
    arr_status_address_1: 'Standard',
    arr_status_address_2: 'Wahlweise',

    arr_explore_sort_0: 'Keine',
    arr_explore_sort_1: 'Beliebtheit',
    arr_explore_sort_2: 'Neu',
    arr_explore_sort_3: 'Preis aufsteigend',
    arr_explore_sort_4: 'Preis absteigend',

    err_empty: 'Felder können nicht leer sein',
    err_signin_wrong: 'Falscher Benutzername oder Passwort',
    err_nav: 'Ungültige Navigation',
    err_verify_code: 'Ungültiger Verifizierungscode',
  },
  vn: {
    header_text_home: 'Trang chủ',
    header_text_explore: 'Khám phá',
    header_text_cart: 'Cửa hàng',
    header_text_account: 'Tài khoản',
    header_text_favorite: 'Yêu thích',
    header_text_notification: 'Thông báo',
    header_text_filter: 'Lọc',
    header_text_recipient_info: 'Thông tin biên nhận',
    header_text_checkout: 'Thủ tục thanh toán',
    header_text_profile: 'Hồ sơ',
    header_text_address: 'Địa chỉ',
    header_text_insert_address: 'Địa chỉ mới',
    header_text_card: 'Thẻ thanh toán',
    header_text_insert_card: 'Thẻ mới',
    header_text_order: 'Đơn đặt hàng của người dùng',
    header_text_order_details: 'Chi tiết đặt hàng',
    header_text_promocodes: 'Mã số quảng',
    header_text_product_detail: 'Thông tin chi tiết sản phẩm',
    header_text_product_ratings: 'xếp hạng',
    header_text_product_insert_rating: 'Xếp hạng mới',
    header_text_update_user: 'Cập nhật thông tin người dùng',

    login_text_header: 'Chào mừng bạn đến với cửa hàng máy tính',
    login_text_sub_header: 'Đăng nhập để tiếp tục',
    login_text_other_signin_option: 'Hoặc đăng nhập bằng',
    login_button_signin: 'Đăng nhập',
    login_button_forgot_password: 'Quên mật khẩu',
    login_button_google_signin: 'Google',
    login_button_signup_1: 'Không có một tài khoản?',
    login_button_signup_2: 'Đăng ký tại đây',

    verify_text_description: 'Chúng tôi sẽ gửi mã xác minh đến email của bạn',
    verify_text_code_description: 'Vui lòng xác minh trước khi hết giờ',
    verify_button_send: 'Gửi',
    verify_button_signin_1: 'Bạn co săn san để tạo một tai khoản?',
    verify_button_signin_2: 'Đăng nhập tại đây',
    verify_button_resend: 'Gửi lại mã xác minh',
    verify_button_verify: 'Xác minh',

    changePass_button_confirm: 'Xác nhận',

    signUp_button_confirm: 'Xác nhận',

    home_text_banner: 'Chào mừng bạn đến với cửa hàng máy tính',
    home_text_popular: 'Phổ biến',
    home_text_best_buy: 'Mua tốt nhất',
    home_text_likeable: 'Bạn có thể thích',
    home_text_see_more: 'Xem thêm',

    explore_text_result: 'Kết quả',
    explore_text_filter: 'Lọc',
    explore_option_header: 'Sắp xếp theo',
    explore_option_1: 'Phổ biến',
    explore_option_2: 'Mới',
    explore_option_3: 'Giá thấp đến cao',
    explore_option_4: 'Giá Cao Đến Thấp',

    cart_text_total: 'Tổng cộng',
    cart_button_order: 'đặt hàng',

    cartRecipient_button_continue: 'Tới thanh toán',

    checkOut_text_product_price: 'Giá các sản phẩm',
    checkOut_text_shipping_price: 'Giá vận chuyển',
    checkOut_text_summary: 'Bản tóm tắt',
    checkOut_button_place_order: 'đặt hàng',

    address_button_insert: 'Thêm địa chỉ mới',

    insertAddress_button_insert: 'Thêm',
    insertAddress_button_update: 'Sửa',

    account_tabHeader_myOrder: 'Đơn hàng của tôi',
    account_tabSub_myOrder: 'Đơn hàng Đang Tiến hành',
    account_tabHeader_adderss: 'Địa chỉ giao hàng',
    account_tabSub_adderss: 'địa chỉ',
    account_tabHeader_payment: 'Phương thức thanh toán',
    account_tabHeader_promo: 'Mã số quảng',
    account_tabSub_promo: 'Mã khuyến mãi',
    account_tabHeader_changePass: 'Đổi mật khẩu',
    account_tabSub_changePass: 'Thay đổi mật khẩu của bạn',
    account_tabHeader_logout: 'Đăng xuất',
    account_tabSub_logout: 'Đăng xuất khỏi tài khoản của bạn',

    order_text_orderNumber: 'Số thứ tự',
    order_text_quantity: 'Số lượng',
    order_text_total: 'Tổng cộng',
    order_text_status: 'Trạng thái',
    order_button_detail: 'Chi tiết',

    orderDetail_textHeader_order: 'Đơn hàng',
    orderDetail_textHeader_product: 'Các sản phẩm',
    orderDetail_textHeader_info: 'Thông tin đặt hàng',
    orderDetail_text_orderNumber: 'No.',
    orderDetail_text_orderDate: 'Ngày đặt hàng',
    orderDetail_text_orderStatus: 'Tình trạng đặt hàng',
    orderDetail_text_shippingAddress: 'Địa chỉ giao hàng',
    orderDetail_text_payment: 'Phương thức thanh toán',
    orderDetail_text_total: 'Tổng cộng',
    orderDetail_text_discount: 'Giảm giá',
    orderDetail_text_discountCode: 'Mã giảm giá',

    placeholder_username: 'tên tài khoản',
    placeholder_fullname: 'Họ và tên',
    placeholder_password: 'Mật khẩu',
    placeholder_password_confirm: 'Xác nhận mật khẩu',
    placeholder_email: 'E-mail',
    placeholder_phoneNumber: 'Số điện thoại',
    placeholder_birthday: 'Sinh nhật',
    placeholder_verify: 'Mã xác nhận',
    placeholder_recipient: 'Người nhận',
    placeholder_addressName: 'Tên địa chỉ',
    placeholder_ward: 'Phường',
    placeholder_district: 'Huyện',
    placeholder_city: 'Thành phố',

    arr_status_order_0: 'Hủy bỏ',
    arr_status_order_1: 'Xử lý',
    arr_status_order_2: 'đóng gói',
    arr_status_order_3: 'Trên đường',
    arr_status_order_4: 'Đã giao hàng',

    arr_status_address_0: 'Hủy kích hoạt',
    arr_status_address_1: 'Mặc định',
    arr_status_address_2: 'Không bắt buộc',

    arr_explore_sort_0: 'Không có',
    arr_explore_sort_1: 'Phổ biến',
    arr_explore_sort_2: 'Mới',
    arr_explore_sort_3: 'Giá tăng dần',
    arr_explore_sort_4: 'Giá giảm dần',

    err_empty: 'Các trường không được để trống',
    err_signin_wrong: 'Tên người dùng hoặc mật khẩu sai',
    err_nav: 'Điều hướng không hợp lệ',
    err_verify_code: 'Mã xác minh không hợp lệ',
  },
  fr: {
    header_text_home: 'Accueil',
    header_text_explore: 'Explorer',
    header_text_cart: 'Chariot',
    header_text_account: 'Compte',
    header_text_favorite: 'Favoris',
    header_text_notification: 'Avis',
    header_text_filter: 'Filtre',
    header_text_recipient_info: 'Informations sur le reçu',
    header_text_checkout: 'Vérification',
    header_text_profile: "Profil de l'utilisateur",
    header_text_address: 'Adresse',
    header_text_insert_address: 'Nouvelle adresse',
    header_text_card: "Carte d'utilisateur",
    header_text_insert_card: 'Nouvelle carte',
    header_text_order: "Commande de l'utilisateur",
    header_text_order_details: 'Détails de la commande',
    header_text_promocodes: 'Promocodes',
    header_text_product_detail: 'Détails du produit',
    header_text_product_ratings: 'Notations',
    header_text_product_insert_rating: 'Nouvelles évaluations',
    header_text_update_user: "Mise à jour des informations sur l'utilisateur",

    login_text_header: 'Bienvenue à Computer Store',
    login_text_sub_header: "S'identifier pour continuer",
    login_text_other_signin_option: 'Ou se connecter avec',
    login_button_signin: "S'identifier",
    login_button_forgot_password: 'Oublier le mot de passe',
    login_button_google_signin: 'Google',
    login_button_signup_1: "Vous n'avez pas de compte ?",
    login_button_signup_2: "S'inscrire ici",

    verify_text_description:
      'Nous vous enverrons un code de vérification à votre adresse e-mail',
    verify_text_code_description:
      "Veuillez vérifier avant l'expiration du délai",
    verify_button_send: 'Envoyer',
    verify_button_signin_1: 'Vous avez déjà un compte ?',
    verify_button_signin_2: "S'inscrire ici",
    verify_button_resend: 'Renvoyer le code de vérification',
    verify_button_verify: 'Vérifier',

    changePass_button_confirm: 'Confirmer',

    signUp_button_confirm: 'Confirmer',

    home_text_banner: 'Bienvenue à Computer Store',
    home_text_popular: 'Populaire',
    home_text_best_buy: 'Best Buy',
    home_text_likeable: 'Vous aimeriez',
    home_text_see_more: 'Voir plus',

    explore_text_result: 'Résultat(s)',
    explore_text_filter: 'Filtre',
    explore_option_header: 'Trier par',
    explore_option_1: 'Popularité',
    explore_option_2: 'Nouveau',
    explore_option_3: 'Prix bas à haut',
    explore_option_4: 'Prix haut à bas',

    cart_text_total: 'Total',
    cart_button_order: 'Passer commande',

    cartRecipient_button_continue: 'Passer à la caisse',

    checkOut_text_product_price: 'Prix du (des) produit(s)',
    checkOut_text_shipping_price: "Prix d'expédition",
    checkOut_text_summary: 'Récapitulatif',
    checkOut_button_place_order: 'Passer la commande',

    address_button_insert: 'Ajouter une nouvelle adresse',

    insertAddress_button_insert: 'Ajouter',
    insertAddress_button_update: 'Modifier',

    account_tabHeader_myOrder: 'Ma commande',
    account_tabSub_myOrder: 'Commande(s) en cours',
    account_tabHeader_adderss: 'Adresse de livraison',
    account_tabSub_adderss: 'Adresse(s)',
    account_tabHeader_payment: 'Méthodes de paiement',
    account_tabHeader_promo: 'Code(s) promotionnel(s)',
    account_tabSub_promo: 'Code(s) promotionnel(s) disponible(s)',
    account_tabHeader_changePass: 'Changer le mot de passe',
    account_tabSub_changePass: 'Modifier votre mot de passe',
    account_tabHeader_logout: 'Déconnexion',
    account_tabSub_logout: 'Déconnexion de votre compte',

    order_text_orderNumber: 'N° de commande',
    order_text_quantity: 'Quantité',
    order_text_total: 'Total',
    order_text_status: 'Statut de la commande',
    order_button_detail: 'Détail de la commande',

    orderDetail_textHeader_order: 'Commande',
    orderDetail_textHeader_product: 'Produit(s)',
    orderDetail_textHeader_info: 'Informations sur la commande',
    orderDetail_text_orderNumber: 'Non.',
    orderDetail_text_orderDate: 'Date de la commande',
    orderDetail_text_orderStatus: 'Statut de la commande',
    orderDetail_text_shippingAddress: 'Adresse de livraison',
    orderDetail_text_payment: 'Mode de paiement',
    orderDetail_text_total: 'Total',
    orderDetail_text_discount: 'Remise',
    orderDetail_text_discountCode: 'Code de réduction',

    placeholder_username: "Nom d'utilisateur",
    placeholder_fullname: 'Nom complet',
    placeholder_password: 'Mot de passe',
    placeholder_password_confirm: 'Confirmer le mot de passe',
    placeholder_email: 'Courriel',
    placeholder_phoneNumber: 'Numéro de téléphone',
    placeholder_birthday: "Date d'anniversaire",
    placeholder_verify: 'Code de vérification',
    placeholder_recipient: 'Destinataire',
    placeholder_addressName: "Nom de l'adresse",
    placeholder_ward: 'Quartier',
    placeholder_district: 'District',
    placeholder_city: 'Ville',

    arr_status_order_0: 'Annuler',
    arr_status_order_1: 'Traitement',
    arr_status_order_2: 'Emballage',
    arr_status_order_3: 'En route',
    arr_status_order_4: 'Livré',

    arr_status_address_0: 'Désactivé',
    arr_status_address_1: 'Par défaut',
    arr_status_address_2: 'Facultatif',

    arr_explore_sort_0: 'Aucun',
    arr_explore_sort_1: 'Popularité',
    arr_explore_sort_2: 'Nouveau',
    arr_explore_sort_3: 'Prix croissant',
    arr_explore_sort_4: 'Prix décroissant',

    err_empty: 'Les champs ne peuvent pas être vides',
    err_signin_wrong: "Nom d'utilisateur ou mot de passe incorrect",
    err_nav: 'Navigation invalide',
    err_verify_code: 'Code de vérification invalide',
  },
  ja: {
    header_text_home: 'ホーム',
    header_text_explore: '探索',
    header_text_cart: 'カート',
    header_text_account: 'アカウント',
    header_text_favorite: 'お気に入り',
    header_text_notification: 'お知らせ',
    header_text_filter: 'フィルター',
    header_text_recipient_info: '領収書情報',
    header_text_checkout: 'チェックアウト',
    header_text_profile: 'プロフィール',
    header_text_address: '住所',
    header_text_insert_address: '新しい住所',
    header_text_card: 'ユーザーカード',
    header_text_insert_card: '新しいカード',
    header_text_order: 'ユーザーオーダー',
    header_text_order_details: 'ご注文内容',
    header_text_promocodes: 'プロモコード',
    header_text_product_detail: '商品詳細',
    header_text_product_ratings: 'レーティング',
    header_text_product_insert_rating: '新しい評価',
    header_text_update_user: 'ユーザー情報の更新',

    login_text_header: 'コンピュータストアへようこそ',
    login_text_sub_header: 'サインインして続ける',
    login_text_other_signin_option: 'または',
    login_button_signin: 'サインイン',
    login_button_forgot_password: 'パスワードを忘れた',
    login_button_google_signin: 'グーグル',
    login_button_signup_1: 'アカウントをお持ちでないですか？',
    login_button_signup_2: 'こちらからサインアップ',

    verify_text_description: 'あなたのEメールに認証コードを送信します。',
    verify_text_code_description: 'タイマーが切れる前に認証してください',
    verify_button_send: '送信',
    verify_button_signin_1: 'アカウントをお持ちですか？',
    verify_button_signin_2: 'こちらからサインイン',
    verify_button_resend: '認証コードを再送する',
    verify_button_verify: '確認する',

    changePass_button_confirm: '確認する',

    signUp_button_confirm: '確認する',

    home_text_banner: 'コンピュータストアへようこそ',
    home_text_popular: '人気',
    home_text_best_buy: 'ベストバイ',
    home_text_likeable: 'お気に入り',
    home_text_see_more: 'もっと見る',

    explore_text_result: '検索結果',
    explore_text_filter: 'フィルター',
    explore_option_header: '並べ替え',
    explore_option_1: '人気順',
    explore_option_2: '新しい順',
    explore_option_3: '価格低い順',
    explore_option_4: '高値から安値へ',

    cart_text_total: '合計',
    cart_button_order: '注文する',

    cartRecipient_button_continue: 'レジへ進む',

    checkOut_text_product_price: '商品価格',
    checkOut_text_shipping_price: '配送価格',
    checkOut_text_summary: '概要',
    checkOut_button_place_order: '注文する',

    address_button_insert: '新しい住所を追加する',

    insertAddress_button_insert: '追加',
    insertAddress_button_update: '編集する',

    account_tabHeader_myOrder: 'マイオーダー',
    account_tabSub_myOrder: '進行中の注文',
    account_tabHeader_adderss: '配送先住所',
    account_tabSub_adderss: '住所',
    account_tabHeader_payment: 'お支払い方法',
    account_tabHeader_promo: 'プロモコード',
    account_tabSub_promo: '利用可能なプロモコード',
    account_tabHeader_changePass: 'パスワードの変更',
    account_tabSub_changePass: 'パスワードの変更',
    account_tabHeader_logout: 'ログアウト',
    account_tabSub_logout: 'アカウントからログアウト',

    order_text_orderNumber: '注文番号',
    order_text_quantity: '数量',
    order_text_total: '合計',
    order_text_status: 'ステータス',
    order_button_detail: '詳細',

    orderDetail_textHeader_order: 'ご注文',
    orderDetail_textHeader_product: '商品',
    orderDetail_textHeader_info: 'ご注文情報',
    orderDetail_text_orderNumber: 'いいえ',
    orderDetail_text_orderDate: 'ご注文日',
    orderDetail_text_orderStatus: 'ご注文状況',
    orderDetail_text_shippingAddress: '配送先住所',
    orderDetail_text_payment: 'お支払い方法',
    orderDetail_text_total: '合計金額',
    orderDetail_text_discount: '割引額',
    orderDetail_text_discountCode: '割引コード',

    placeholder_username: 'ユーザー名',
    placeholder_fullname: 'フルネーム',
    placeholder_password: 'パスワード',
    placeholder_password_confirm: 'パスワードの確認',
    placeholder_email: 'Eメール',
    placeholder_phoneNumber: '電話番号',
    placeholder_birthday: '誕生日',
    placeholder_verify: '認証コード',
    placeholder_recipient: '受取人',
    placeholder_addressName: 'ご住所',
    placeholder_ward: '区',
    placeholder_district: '区',
    placeholder_city: '市区町村',

    arr_status_order_0: 'キャンセル',
    arr_status_order_1: '処理',
    arr_status_order_2: '梱包',
    arr_status_order_3: '配送中',
    arr_status_order_4: '配送中',

    arr_status_address_0: '無効',
    arr_status_address_1: 'デフォルト',
    arr_status_address_2: 'オプション',

    arr_explore_sort_0: 'なし',
    arr_explore_sort_1: '人気',
    arr_explore_sort_2: '新しい',
    arr_explore_sort_3: '昇順価格',
    arr_explore_sort_4: '価格降順',

    err_empty: 'フィールドを空にすることはできません',
    err_signin_wrong: 'ユーザー名またはパスワードが間違っています',
    err_nav: '無効なナビゲーション',
    err_verify_code: '認証コードが無効です',
  },
};

export const useLanguage = () => {
  const {localeIdentifier} = NativeModules.I18nManager;
  let locale = localeIdentifier.slice(0, 2);
  if (languageTheme[locale] == null) {
    return languageTheme['en'];
  }
  let language = languageTheme['ja'];
  console.log('language', language);
  return language;
};
